select b.wo, b.wo_description, b.status, b.wo_category, b.ac, b.ac_type, b.ac_series, b.expenditure, b.location, b.site, b.schedule_start_date, b.schedule_completion_date, b.wo_man_hrs, b.priority, ROUND((TO_DATE(b.schedule_completion_date, 'DD-MON-YY HH24:MI') - TO_DATE(b.schedule_start_date, 'DD-MON-YY HH24:MI') + 1),0) as DAYS_IN_CHECK, b.project as HMV_DRIVER, b.approval as PLANNER, (select notes_text from note_pad np where np.notes = (select notes from wo where wo = b.wo)) as NOTES, max(eo.ground_time_require) as GROUND_TIME_REQD
from
(select a.wo,
       a.wo_description,
       a.status,
       a.wo_category,
       a.ac,
       a.ac_type,
       a.ac_series,
       a.expenditure,
       a.location,
       a.site,
       a.schedule_start_date || to_char ( nvl ( a.schedule_start_hour,0 ) ,'00' ) || ':'|| trim ( to_char ( nvl ( a.schedule_start_minute,0 ) ,'00' ) ) as schedule_start_date,
       a.schedule_org_completion_date || to_char ( nvl ( a.schedule_org_completion_hour,0 ) ,'00' ) || ':' || trim ( to_char ( nvl ( a.schedule_org_completion_minute,0 ) ,'00' ) ) as schedule_completion_date,
       a.wo_man_hrs,
       a.priority,
       a.project,
       a.approval
  from ( SELECT WO.WO ,
                WO.wo_description ,
                WO.STATUS ,
                WO.wo_category ,
                WO.AC ,
                am.ac_type ,
                am.ac_series ,
                WO.expenditure ,
                WO.location ,
                WO.site ,
                WO.schedule_start_date ,
                wo.schedule_start_hour,
                wo.schedule_start_minute,
                WO.schedule_org_completion_date,
                wo.schedule_org_completion_hour ,
                wo.schedule_org_completion_minute ,
                wo.priority,
                wo.project,
                wo.approval,
                NVL(SUM ( WTCI.man_hours ),0) AS WO_MAN_HRS
          FROM wo INNER JOIN ac_master am ON wo.ac = am.ac LEFT OUTER JOIN wo_task_card_item wtci ON wo.wo = wtci.wo 
          WHERE wo.status IN ( 'GENERATE','OPEN' )
            and wo.nh_wo is null
          GROUP BY WO.WO ,
                WO.order_type ,
                WO.wo_description ,
                WO.STATUS ,
                WO.wo_category ,
                WO.AC ,
                am.ac_type ,
                am.ac_series ,
                WO.expenditure ,
                WO.location ,
                WO.site ,
                WO.schedule_start_date,
                wo.schedule_start_hour,
                wo.schedule_start_minute,
                WO.schedule_org_completion_date,
                wo.schedule_org_completion_hour,
                wo.schedule_org_completion_minute,
                wo.priority, 
                wo.project,
                wo.approval) a
) b LEFT OUTER JOIN wo_engineering_order weo on weo.wo = b.wo LEFT join engineering_order eo on weo.eo = eo.eo
 group by
 b.wo,
       b.wo_description,
       b.status,
       b.wo_category,
       b.ac,
       b.ac_type,
       b.ac_series,
       b.expenditure,
       b.location,
       b.site,
       b.schedule_start_date,
       b.schedule_completion_date,
       b.wo_man_hrs,
       b.priority,
       b.project,
       b.approval
order by b.wo_man_hrs desc;